# Generated by Django 6.0 on 2025-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_key', models.CharField(choices=[('csit', 'BSc CSIT'), ('bca', 'BCA'), ('bbm', 'BBM'), ('bbs', 'BBS')], max_length=10, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('what', models.TextField()),
                ('how', models.TextField()),
                ('why', models.TextField()),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='academics')),
                ('image2', models.ImageField(upload_to='academics')),
            ],
        ),
    ]
