# Generated by Django 6.0 on 2025-12-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_key', models.CharField(choices=[('science', 'Science'), ('management', 'Management'), ('law', 'Law'), ('csit', 'BSc CSIT'), ('bca', 'BCA'), ('bbm', 'BBM'), ('bbs', 'BBS')], max_length=15, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='academics')),
                ('level', models.CharField(choices=[('plus2', '+2 (NEB)'), ('bachelors', 'Bachelors')], max_length=12)),
            ],
        ),
    ]
