# Generated by Django 6.0 on 2025-12-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('plus2', '+2 (NEB)'), ('bachelors', 'Bachelors')], max_length=12)),
                ('question', models.CharField(max_length=150)),
                ('answer', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
