# Generated by Django 6.0 on 2025-12-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsPlus2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_key', models.CharField(choices=[('science', 'Science'), ('management', 'Management'), ('law', 'Law')], max_length=10, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='academics')),
            ],
        ),
    ]
