# Generated by Django 6.0 on 2025-12-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_academicsplus2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicsplus2',
            old_name='image1',
            new_name='image2',
        ),
    ]
