# Generated by Django 6.0 on 2025-12-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image1_academicsplus2_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicsplus2',
            old_name='image2',
            new_name='image1',
        ),
    ]
