# Generated by Django 6.0 on 2026-01-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_academics_criteria_academics_in_short_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='in_short',
        ),
    ]
