# Generated by Django 6.0 on 2026-01-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_academics_in_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='skills',
        ),
    ]
