# Generated by Django 6.0 on 2026-01-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_academics_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
