# Generated by Django 6.0 on 2026-01-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty')),
                ('description', models.TextField(help_text='Designation, subjects taught, responsibilities, etc.')),
                ('category', models.CharField(choices=[('MANAGEMENT', 'College Management'), ('HOD', 'Heads of Departments'), ('TEACHING', 'Teaching Faculty'), ('NON_TEACHING', 'Non-Teaching Staff')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='academics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='academics'),
        ),
    ]
